# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('tel', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15)),
                ('result', models.CharField(max_length=150, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=45)),
                ('end', models.CharField(max_length=45)),
                ('wmid', models.CharField(max_length=15)),
                ('status', models.CharField(default='init', max_length=45)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('tel', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=750)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='Wm',
            fields=[
                ('wmid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'wm',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washingmachine.UserInfo'),
        ),
    ]
