# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washingmachine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=45)),
                ('should_pay', models.CharField(default='0', max_length=45)),
                ('years', models.CharField(default='0', max_length=45)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.CharField(default='0', max_length=45),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.CharField(default='0', max_length=45),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='washingmachine.Product'),
        ),
    ]
